my-config.name: default eureka

server:
  port: 8760
spring:
  profiles: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 5 # 서버가 요청을 받기 전 대기할 초기 시간 (5ms, 운영 환경에선 삭제 필요)
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false

---

my-config.name: peer1 eureka
server:
  port: 8762
spring:
  profiles: peer1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    hostname: peer1
  server:
    wait-time-in-ms-when-sync-empty: 5 # 서버가 요청을 받기 전 대기할 초기 시간 (5ms, 운영 환경에선 삭제 필요)
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8763/eureka

---
my-config.name: peer1 eureka
server:
  port: 8763
spring:
  profiles: peer1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    hostname: peer1
  server:
    wait-time-in-ms-when-sync-empty: 5 # 서버가 요청을 받기 전 대기할 초기 시간 (5ms, 운영 환경에선 삭제 필요)
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8762/eureka

---


