my-config.name: default eureka

server:
  port: 8761
spring:
  profiles: default
  cloud:
    bus:
      # Bus로 설정변경 새로고침 활성화
      enabled: true
      # bus-refresh EndPoint 활성화 호출시 전체 Config Bus Client 들에게 메세지 전송
      refresh:
        enabled: true
      env:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
  endpoint:
    shutdown:
      enabled: true

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 5 # 서버가 요청을 받기 전 대기할 초기 시간 (5ms, 운영 환경에선 삭제 필요)
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: http://localhost:8761/eureka/


