my-config.name: default eureka

server:
  port: 8761
spring:
  profiles: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 5 # 서버가 요청을 받기 전 대기할 초기 시간 (5ms, 운영 환경에선 삭제 필요)
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: http://localhost:8761/eureka


