eureka:
  instance:
    prefer-ip-address: true # 서비스 이름 대신 IP 주소 등록
  client:
    register-with-eureka: true # 유레카 서버에 서비스 등록
    fetch-registry: true # 레지스트리 정보를 로컬에 캐싱
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/board?characterEncoding=utf8
    username: root
    password: Qkrwnsgh1!
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update #create ? ???? Data?? ?? ?. ?? ???? update ???? ???? none ?

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      evenConsumerBufferSize: 10
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instance:
    backendA:
      baseConfig: default
      waitDurationInOpenState: 5000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled:true
