security:
  oauth2:
    client-id: auth_id
    client_secret: auth_secret
    jwt:
      key-value: jwt_secret_key

spring:
  application:
    name: oauth2-service
  datasource:
    url: jdbc:mysql://localhost:3306/board?characterEncoding=utf8
    username: root
    password: Qkrwnsgh1!
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update #create ? ???? Data?? ?? ?. ?? ???? update ???? ???? none ?